# Generated by Django 4.0.6 on 2022-07-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_transaction_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
